server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: Reservation
          uri: http://localhost:8081
          predicates:
            - Path=/reservationProcessings/** 
        - id: Payment
          uri: http://localhost:8082
          predicates:
            - Path=/paymentProcessings/** 
        - id: Delivery
          uri: http://localhost:8083
          predicates:
            - Path=/deliveryProcessings/** 
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: Reservation
          uri: http://Reservation:8080
          predicates:
            - Path=/reservationProcessings/** 
        - id: Payment
          uri: http://Payment:8080
          predicates:
            - Path=/paymentProcessings/** 
        - id: Delivery
          uri: http://Delivery:8080
          predicates:
            - Path=/deliveryProcessings/** 
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
